create table ipo_info(
id bigint primary key,
company_logo_path text,
company_name varchar(20),
price_band varchar(30),
open varchar(30),
close varchar(40),
issue_size varchar(30),
issue_type varchar(40),
listing_date varchar(40),
status int,
ipo_price varchar(40),
listing_price varchar(30),
listing_gain varchar(40),
cmp varchar(40),
current_return varchar(40),
rhp varchar(30),
drhp varchar(40));